- lib/handle.ts
获取拼音时，在word中包含dict中的某个词的情况下，将获取该词拼音的步骤放入找到该词后，减少无词情况下的查找速度
> feat: 提高拼音查询速度

- .travis.yml
> feat: 修改 travis node 版本

- package.json
- rollup.config.js
release(3.15.2): 修复 node 环境 import 报错问题
> release(3.15.2): 修复 node 环境 import 报错问题

- CHANGELOG.md
- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- package.json
- test/separator.test.js
- types/core/pinyin/index.d.ts
> release(3.16.0): 新增支持自定义拼音间分隔符

- lib/common/ac.ts
- lib/core/custom/index.ts
- lib/core/pinyin/handle.ts
- lib/data/surname.ts
- package.json
- types/common/ac.d.ts
[优化初始 AC 自动机构建时间](https://github.com/zh-lx/pinyin-pro/commit/54a47dbd93f766789175f4945fa350569909231a)
> 优化初始 AC 自动机构建时间

- CHANGELOG.md
> docs: update change log

- lib/core/custom/index.ts
- lib/core/pinyin/handle.ts
- lib/core/polyphonic/index.ts
- lib/index.ts
- test/custom.test.js
- types/core/custom/index.d.ts
- types/index.d.ts
custom effect for multiple and polyphonic
> feat: custom effect for multiple and polyphonic

- CHANGELOG.md
- package.json
- 【feat】`customPinyin`: `customPinyin` 支持对 `multiple` 和 `polyphonic` 生效
> release: 3.19.0

- lib/core/pinyin/middlewares.ts
- test/tone-type.test.js
> fix: 修复非中文 toneType: 'num' 时出现额外数字的问题

- lib/core/html/index.ts
- test/html.test.js
- types/common/type.d.ts
- types/core/convert/index.d.ts
- types/core/custom/index.d.ts
- types/core/html/index.d.ts
- types/core/match/index.d.ts
- types/core/pinyin/handle.d.ts
> feat: html 增加自定义 classname

- lib/common/constant.ts
- lib/common/utils.ts
- lib/data/dict-number.ts
> feat: 数字词库增加"几"

- .editorconfig
> feat: 增加 editorconfig 配置文件，统一缩进格式

- lib/core/pinyin/handle.ts
- test/multiple.test.js
> fix: 修复 multiple 和 surname 一同使用的情景

- lib/common/ac.ts
> optimize: 优化 AC 自动机构建性能

- lib/core/pinyin/handle.ts
- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- lib/core/polyphonic/index.ts
- test/all.test.js
- test/multiple.test.js
- test/polyphonic.test.js
- types/core/pinyin/handle.d.ts
- types/core/pinyin/index.d.ts
- types/core/pinyin/middlewares.d.ts
- types/core/polyphonic/index.d.ts
> feat: pinyin all 模式新增 polyphonic 和 inZhRange 属性

- lib/common/segmentit/index.ts
- lib/common/segmentit/max-probability.ts
- lib/common/segmentit/min-tokenization.ts
- lib/core/convert/index.ts
- lib/core/custom/index.ts
- lib/core/dict/index.ts
- lib/core/pinyin/handle.ts
- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- test/convert.test.js
- test/custom.test.js
- test/dict.test.js
- test/match.test.js
- test/pattern.test.js
- test/segmentit.test.js
- test/special.test.js
- test/toneSandhi.test.js
- test/v.test.js
- types/common/segmentit/index.d.ts
> test: 完善测试用例

- lib/core/polyphonic/index.ts
- test/polyphonic.test.js
> fix: 修复 polyphonic 对非中文字符的处理

- lib/core/pinyin/handle.ts
- lib/core/pinyin/index.ts
- types/core/pinyin/handle.d.ts
- types/core/pinyin/index.d.ts
> fix: 修复 alias 导致的 type 报错

- lib/common/segmentit/index.ts
- lib/common/type.ts
- lib/core/pinyin/handle.ts
- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- test/surname.test.js
- types/common/segmentit/index.d.ts
- types/common/type.d.ts
- types/core/pinyin/handle.d.ts
- types/core/pinyin/index.d.ts
- types/core/pinyin/middlewares.d.ts
> feat: 支持 surname head 模式

- lib/data/special.ts
- test/special.test.js
> Feature support reduplication

- lib/common/segmentit/index.ts
- lib/data/special.ts
- lib/data/surname.ts
> feat: 自定义词典词 length 适配双字节字符

- README.md
> chore: 注释语义错误

- lib/common/utils.ts
- lib/core/dict/index.ts
- lib/core/html/index.ts
- lib/core/match/index.ts
> chore: 优化部分代码

- lib/core/custom/index.ts
- lib/data/dict1.ts
- test/type.test.js
- types/core/custom/index.d.ts
- types/data/dict1.d.ts
> fix: 修复 .d.ts 文件中 alias 报错问题

- CHANGELOG.md
- lib/index.ts
- package.json
- types/index.d.ts
> feat: 支持外部调用 `getInitialAndFinal`、`getFinalParts`、`getNumOfTone` 等 API

- CHANGELOG.md
- README.md
> docs: 更新文档链接

- lib/core/pinyin/handle.ts
- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- lib/core/segment/index.ts
- lib/core/segment/middlewares.ts
- lib/index.ts
- test/all.test.js
- test/segment.test.js
- types/core/pinyin/handle.d.ts
- types/core/pinyin/index.d.ts
- types/core/pinyin/middlewares.d.ts
- types/core/segment/index.d.ts
- types/core/segment/middlewares.d.ts
- types/index.d.ts
增加 `segment` 分词 api。
close #259
> feat: add segment api

- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- test/nonZh.test.js
feat: 增加 nonZhScope 属性
close #261
> feat: 增加 nonZhScope 属性

- lib/core/segment/middlewares.ts
- test/segment.test.js
fix: 修复 segment api 文字最后的标点符号丢失问题
> fix: 修复 segment api 文字最后的标点符号丢失问题

- lib/core/html/index.ts
- test/html.test.js
> feat: 优化 html 自定义类名显示

- lib/core/html/index.ts
- test/html.test.js
feat: html api 支持不输出 rp 标签
close #270
> feat: html api 支持不输出 rp 标签

- lib/core/pinyin/index.ts
- lib/core/pinyin/middlewares.ts
- test/v.test.js
- types/core/pinyin/index.d.ts
> feat: 支持自定义 ü 要替换为的字符串
